version: "3.7"

services:
  api:
    build: ./api
  nginx:
    image: nginx:1.16-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx_conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./web/build:/var/www/spoilers/static
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  ui-build:
    restart: "no"
    build: ./web
    volumes:
      - ./web/build:/code/build
    entrypoint: "gulp"